; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Untitled_Start
Untitled_StartDisarkGenerateExternalLabel

Untitled_DisarkByteRegionStart0
	db "AT20"
Untitled_DisarkPointerRegionStart1
	dw Untitled_ArpeggioTable	; The address of the Arpeggio table.
	dw Untitled_PitchTable	; The address of the Pitch table.
	dw Untitled_InstrumentTable	; The address of the Instrument table.
	dw Untitled_EffectBlockTable	; The address of the Effect Block table.
Untitled_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Untitled_DisarkPointerRegionStart2
	dw Untitled_Subsong0_Start
Untitled_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Untitled_ArpeggioTable
Untitled_DisarkPointerRegionStart3
Untitled_DisarkPointerRegionEnd3

; Declares all the Pitches.
Untitled_PitchTable
Untitled_DisarkPointerRegionStart4
Untitled_DisarkPointerRegionEnd4

; Declares all the Instruments.
Untitled_InstrumentTable
Untitled_DisarkPointerRegionStart5
	dw Untitled_EmptyInstrument
	dw Untitled_Instrument1
Untitled_DisarkPointerRegionEnd5

Untitled_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Untitled_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Untitled_Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Untitled_EffectBlockTable
Untitled_DisarkPointerRegionStart6
	dw Untitled_EffectBlock_P4P1	; Index 0
	dw Untitled_EffectBlock_P4P2	; Index 1
	dw Untitled_EffectBlock_P4P0	; Index 2
	dw Untitled_EffectBlock_P4P4	; Index 3
	dw Untitled_EffectBlock_P4P3	; Index 4
	dw Untitled_EffectBlock_P4P5	; Index 5
Untitled_DisarkPointerRegionEnd6

Untitled_EffectBlock_P4P0
	db 4, 0
Untitled_EffectBlock_P4P1
	db 4, 1
Untitled_EffectBlock_P4P2
	db 4, 2
Untitled_EffectBlock_P4P3
	db 4, 3
Untitled_EffectBlock_P4P4
	db 4, 4
Untitled_EffectBlock_P4P5
	db 4, 5

Untitled_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Untitled_Subsong0_DisarkByteRegionStart0
Untitled_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 9	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 33	; Base note index (>=0).

Untitled_Subsong0_Linker
Untitled_Subsong0_DisarkPointerRegionStart1
; Position 0
Untitled_Subsong0_Linker_Loop
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track1
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 1
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_LinkerBlock1

; Position 2
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_LinkerBlock1

; Position 3
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock1

; Position 4
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_LinkerBlock1

; Position 5
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_LinkerBlock1

; Position 6
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_LinkerBlock1

; Position 7
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track14
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_LinkerBlock1

; Position 8
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_LinkerBlock1

; Position 9
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_LinkerBlock1

Untitled_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Untitled_Subsong0_DisarkWordForceReference2
	dw Untitled_Subsong0_Linker_Loop

Untitled_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference3
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference4
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference5
	dw Untitled_Subsong0_SpeedTrack1	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference6
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.

Untitled_Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track1
	db 192
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 20	; Waits for 21 lines.

	db 65
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 28	; Escape note (28).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track2
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 223
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 95
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 16	; Waits for 17 lines.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 29
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track3
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 183
	db 1	; New Instrument (1).
	db 119
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 119
	db 4	; Index to an effect block.
	db 55
	db 115
	db 0	; Index to an effect block.
	db 115
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 118
	db 0	; Index to an effect block.
	db 118
	db 1	; Index to an effect block.
	db 54
	db 118
	db 3	; Index to an effect block.
	db 114
	db 0	; Index to an effect block.
	db 114
	db 1	; Index to an effect block.
	db 50
	db 114
	db 3	; Index to an effect block.
	db 114
	db 5	; Index to an effect block.
	db 50
	db 61, 7	; Waits for 8 lines.

	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 53
	db 117
	db 3	; Index to an effect block.
	db 115
	db 0	; Index to an effect block.
	db 115
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 71
	db 2	; Index to an effect block.
	db 7
	db 5
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 0
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 95
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 16	; Waits for 17 lines.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 29
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track5
	db 61, 7	; Waits for 8 lines.

	db 128
	db 1	; New Instrument (1).
	db 61, 12	; Waits for 13 lines.

	db 75
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 24
	db 91
	db 1	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 102
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track6
	db 61, 47	; Waits for 48 lines.

	db 230
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track7
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 180
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 61, 6	; Waits for 7 lines.

	db 50
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 49
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track8
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 177
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 61, 6	; Waits for 7 lines.

	db 46
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track9
	db 61, 7	; Waits for 8 lines.

	db 192
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 71
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 64
	db 2	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 71
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track10
	db 134
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 64
	db 2	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 20	; Waits for 21 lines.

	db 65
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track11
	db 61, 9	; Waits for 10 lines.

	db 223
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 95
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 16	; Waits for 17 lines.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 29
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track12
	db 130
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 28	; Escape note (28).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 64
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 119
	db 4	; Index to an effect block.
	db 55
	db 115
	db 0	; Index to an effect block.
	db 115
	db 1	; Index to an effect block.
	db 119
	db 0	; Index to an effect block.
	db 119
	db 1	; Index to an effect block.
	db 118
	db 0	; Index to an effect block.
	db 118
	db 1	; Index to an effect block.
	db 54
	db 118
	db 3	; Index to an effect block.
	db 114
	db 0	; Index to an effect block.
	db 114
	db 1	; Index to an effect block.
	db 50
	db 114
	db 3	; Index to an effect block.
	db 114
	db 5	; Index to an effect block.
	db 50
	db 61, 7	; Waits for 8 lines.

	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 53
	db 117
	db 3	; Index to an effect block.
	db 115
	db 0	; Index to an effect block.
	db 115
	db 1	; Index to an effect block.
	db 117
	db 0	; Index to an effect block.
	db 117
	db 1	; Index to an effect block.
	db 71
	db 2	; Index to an effect block.
	db 7
	db 5
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 2
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track13
	db 61, 9	; Waits for 10 lines.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 95
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 16	; Waits for 17 lines.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 93
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 29
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track14
	db 128
	db 1	; New Instrument (1).
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 12	; Waits for 13 lines.

	db 75
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 76
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 24
	db 91
	db 1	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 71
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 127
	db 28	; Escape note (28).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track15
	db 191
	db 28	; Escape note (28).
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Untitled_Subsong0_SpeedTrack0
	db 16	; Value: 8.
	db 253	; Wait for 127 lines.
Untitled_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Untitled_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Untitled_Subsong0_DisarkByteRegionEnd0
