; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Untitled_Start
Untitled_StartDisarkGenerateExternalLabel

Untitled_DisarkByteRegionStart0
	db "AT20"
Untitled_DisarkPointerRegionStart1
	dw Untitled_ArpeggioTable	; The address of the Arpeggio table.
	dw Untitled_PitchTable	; The address of the Pitch table.
	dw Untitled_InstrumentTable	; The address of the Instrument table.
	dw Untitled_EffectBlockTable	; The address of the Effect Block table.
Untitled_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Untitled_DisarkPointerRegionStart2
	dw Untitled_Subsong0_Start
Untitled_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Untitled_ArpeggioTable
Untitled_DisarkPointerRegionStart3
Untitled_DisarkPointerRegionEnd3

; Declares all the Pitches.
Untitled_PitchTable
Untitled_DisarkPointerRegionStart4
Untitled_DisarkPointerRegionEnd4

; Declares all the Instruments.
Untitled_InstrumentTable
Untitled_DisarkPointerRegionStart5
	dw Untitled_EmptyInstrument
	dw Untitled_Instrument1
	dw Untitled_Instrument2
Untitled_DisarkPointerRegionEnd5

Untitled_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Untitled_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Untitled_Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument2
	db 5	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Untitled_EffectBlockTable
Untitled_DisarkPointerRegionStart6
	dw Untitled_EffectBlock_P4P2	; Index 0
Untitled_DisarkPointerRegionEnd6

Untitled_EffectBlock_P4P2
	db 4, 2

Untitled_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Untitled_Subsong0_DisarkByteRegionStart0
Untitled_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 14	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 17	; Base note index (>=0).

Untitled_Subsong0_Linker
Untitled_Subsong0_DisarkPointerRegionStart1
; Position 0
Untitled_Subsong0_Linker_Loop
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track1
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 1
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_LinkerBlock1

; Position 2
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock1

; Position 3
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_LinkerBlock1

; Position 4
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_LinkerBlock1

; Position 5
	dw Untitled_Subsong0_Track14
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_LinkerBlock1

; Position 6
	dw Untitled_Subsong0_Track16
	dw Untitled_Subsong0_Track17
	dw Untitled_Subsong0_Track18
	dw Untitled_Subsong0_LinkerBlock1

; Position 7
	dw Untitled_Subsong0_Track19
	dw Untitled_Subsong0_Track20
	dw Untitled_Subsong0_Track21
	dw Untitled_Subsong0_LinkerBlock1

; Position 8
	dw Untitled_Subsong0_Track22
	dw Untitled_Subsong0_Track23
	dw Untitled_Subsong0_Track24
	dw Untitled_Subsong0_LinkerBlock1

; Position 9
	dw Untitled_Subsong0_Track14
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_LinkerBlock1

; Position 10
	dw Untitled_Subsong0_Track25
	dw Untitled_Subsong0_Track26
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_LinkerBlock1

; Position 11
	dw Untitled_Subsong0_Track27
	dw Untitled_Subsong0_Track28
	dw Untitled_Subsong0_Track29
	dw Untitled_Subsong0_LinkerBlock1

; Position 12
	dw Untitled_Subsong0_Track30
	dw Untitled_Subsong0_Track28
	dw Untitled_Subsong0_Track29
	dw Untitled_Subsong0_LinkerBlock1

; Position 13
	dw Untitled_Subsong0_Track31
	dw Untitled_Subsong0_Track32
	dw Untitled_Subsong0_Track21
	dw Untitled_Subsong0_LinkerBlock1

; Position 14
	dw Untitled_Subsong0_Track22
	dw Untitled_Subsong0_Track23
	dw Untitled_Subsong0_Track24
	dw Untitled_Subsong0_LinkerBlock1

Untitled_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Untitled_Subsong0_DisarkWordForceReference2
	dw Untitled_Subsong0_Linker_Loop

Untitled_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference3
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference4
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference5
	dw Untitled_Subsong0_SpeedTrack1	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference6
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.

Untitled_Subsong0_Track0
	db 221
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 18	; Waits for 19 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 27
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 27
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track1
	db 245
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 18	; Waits for 19 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track2
	db 197
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 12
	db 61, 6	; Waits for 7 lines.

	db 17
	db 61, 14	; Waits for 15 lines.

	db 3
	db 61, 6	; Waits for 7 lines.

	db 10
	db 61, 6	; Waits for 7 lines.

	db 15
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track3
	db 157
	db 1	; New Instrument (1).
	db 61, 18	; Waits for 19 lines.

	db 25
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 25
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 29
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 28
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track4
	db 181
	db 1	; New Instrument (1).
	db 61, 18	; Waits for 19 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track5
	db 141
	db 2	; New Instrument (2).
	db 61, 6	; Waits for 7 lines.

	db 20
	db 61, 6	; Waits for 7 lines.

	db 25
	db 61, 14	; Waits for 15 lines.

	db 12
	db 61, 6	; Waits for 7 lines.

	db 19
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track6
	db 136
	db 1	; New Instrument (1).
	db 61, 30	; Waits for 31 lines.

	db 8
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track7
	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track8
	db 145
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track9
	db 169
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 36
	db 61, 10	; Waits for 11 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track10
	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track11
	db 133
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track12
	db 160
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track13
	db 129
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 1
	db 60	; Waits for 1 line.

	db 1
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track14
	db 145
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 12
	db 61, 10	; Waits for 11 lines.

	db 17
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 17
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 24
	db 61, 18	; Waits for 19 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 60	; Waits for 1 line.

	db 25
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 27
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track15
	db 173
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 51
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 53
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 63
	db 74	; Escape note (74).
	db 60	; Waits for 1 line.

	db 63
	db 75	; Escape note (75).
	db 60	; Waits for 1 line.

	db 63
	db 77	; Escape note (77).
	db 61, 6	; Waits for 7 lines.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track16
	db 157
	db 1	; New Instrument (1).
	db 61, 19	; Waits for 20 lines.

	db 29
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 60	; Waits for 1 line.

	db 27
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 25
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 27
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 25
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track17
	db 177
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 63
	db 73	; Escape note (73).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 63
	db 73	; Escape note (73).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 63
	db 73	; Escape note (73).
	db 60	; Waits for 1 line.

	db 55
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 63
	db 73	; Escape note (73).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 60	; Waits for 1 line.

	db 51
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 51
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 60	; Waits for 1 line.

	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track18
	db 141
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 20
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track19
	db 150
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 25
	db 61, 14	; Waits for 15 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 22
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 22
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track20
	db 177
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 53
	db 61, 6	; Waits for 7 lines.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 51
	db 61, 6	; Waits for 7 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track21
	db 134
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 6
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track22
	db 147
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 23
	db 61, 14	; Waits for 15 lines.

	db 26
	db 61, 6	; Waits for 7 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track23
	db 175
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 60	; Waits for 1 line.

	db 39
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track24
	db 135
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track25
	db 157
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 32
	db 61, 6	; Waits for 7 lines.

	db 31
	db 61, 6	; Waits for 7 lines.

	db 28
	db 61, 14	; Waits for 15 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track26
	db 191
	db 73	; Escape note (73).
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 63
	db 76	; Escape note (76).
	db 61, 6	; Waits for 7 lines.

	db 63
	db 75	; Escape note (75).
	db 61, 6	; Waits for 7 lines.

	db 55
	db 61, 14	; Waits for 15 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track27
	db 153
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 29
	db 61, 6	; Waits for 7 lines.

	db 28
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track28
	db 151
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 29
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 32
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 35
	db 60	; Waits for 1 line.

	db 41
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 44
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 61, 14	; Waits for 15 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track29
	db 139
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track30
	db 153
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 29
	db 61, 6	; Waits for 7 lines.

	db 28
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 14	; Waits for 15 lines.

	db 21
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track31
	db 150
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 25
	db 61, 6	; Waits for 7 lines.

	db 24
	db 61, 6	; Waits for 7 lines.

	db 20
	db 61, 14	; Waits for 15 lines.

	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track32
	db 177
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 54
	db 61, 6	; Waits for 7 lines.

	db 53
	db 61, 6	; Waits for 7 lines.

	db 48
	db 61, 14	; Waits for 15 lines.

	db 44
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Untitled_Subsong0_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.
Untitled_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Untitled_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Untitled_Subsong0_DisarkByteRegionEnd0
