; Intro, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Intro_Start
Intro_StartDisarkGenerateExternalLabel

Intro_DisarkByteRegionStart0
	db "AT20"
Intro_DisarkPointerRegionStart1
	dw Intro_ArpeggioTable	; The address of the Arpeggio table.
	dw Intro_PitchTable	; The address of the Pitch table.
	dw Intro_InstrumentTable	; The address of the Instrument table.
	dw Intro_EffectBlockTable	; The address of the Effect Block table.
Intro_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Intro_DisarkPointerRegionStart2
	dw Intro_Subsong0_Start
Intro_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Intro_ArpeggioTable
Intro_DisarkPointerRegionStart3
	dw Intro_Arpeggio1
Intro_DisarkPointerRegionEnd3

Intro_Arpeggio1
	db 1	; The speed.

	db 0
	db 0
	db 9
	db -12
	db 18
	db -128
Intro_DisarkWordForceReference4
	dw Intro_Arpeggio1 + 0 + 1	; Loop.

; Declares all the Pitches.
Intro_PitchTable
Intro_DisarkPointerRegionStart5
	dw Intro_Pitch1
Intro_DisarkPointerRegionEnd5

Intro_Pitch1
	db 1	; The speed.

	dw 0
Intro_Pitch1_GotoNextForLine0
Intro_DisarkWordForceReference6
	dw Intro_Pitch1_GotoNextForLine0 + 2
	dw 0
Intro_Pitch1_GotoNextForLine1
Intro_DisarkWordForceReference7
	dw Intro_Pitch1_GotoNextForLine1 + 2
	dw 0
Intro_Pitch1_GotoNextForLine2
Intro_DisarkWordForceReference8
	dw Intro_Pitch1_GotoNextForLine2 + 2
	dw -1
Intro_Pitch1_GotoNextForLine3
Intro_DisarkWordForceReference9
	dw Intro_Pitch1_GotoNextForLine3 + 2
	dw -2
Intro_Pitch1_GotoNextForLine4
Intro_DisarkWordForceReference10
	dw Intro_Pitch1_GotoNextForLine4 + 2
	dw 2
Intro_DisarkWordForceReference11
	dw Intro_Pitch1 + 4 * 0 + 1

; Declares all the Instruments.
Intro_InstrumentTable
Intro_DisarkPointerRegionStart12
	dw Intro_EmptyInstrument
	dw Intro_Instrument1
	dw Intro_Instrument2
	dw Intro_Instrument3
	dw Intro_Instrument4
Intro_DisarkPointerRegionEnd12

Intro_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Intro_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Intro_Instrument1
	db 9	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 6	; Loop to silence.

Intro_Instrument2
	db 1	; The speed (>0, 0 for 256).
Intro_Instrument2_Loop	db 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
Intro_DisarkWordForceReference13
	dw Intro_Instrument2_Loop	; Loop here.

Intro_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Intro_Instrument4
	db 8	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Intro_EffectBlockTable
Intro_DisarkPointerRegionStart14
	dw Intro_EffectBlock_P5P1P6P0	; Index 0
	dw Intro_EffectBlock_P4P0	; Index 1
	dw Intro_EffectBlock_P4P2	; Index 2
	dw Intro_EffectBlock_P10P0	; Index 3
Intro_DisarkPointerRegionEnd14

Intro_EffectBlock_P4P0
	db 4, 0
Intro_EffectBlock_P4P2
	db 4, 2
Intro_EffectBlock_P5P1P6P0
	db 5, 1, 6, 0
Intro_EffectBlock_P10P0
	db 10, 0

Intro_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Intro_Subsong0_DisarkByteRegionStart0
Intro_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 7	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 29	; Base note index (>=0).

Intro_Subsong0_Linker
Intro_Subsong0_DisarkPointerRegionStart1
; Position 0
Intro_Subsong0_Linker_Loop
	dw Intro_Subsong0_Track0
	dw Intro_Subsong0_Track1
	dw Intro_Subsong0_Track2
	dw Intro_Subsong0_LinkerBlock0

; Position 1
	dw Intro_Subsong0_Track3
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track5
	dw Intro_Subsong0_LinkerBlock1

; Position 2
	dw Intro_Subsong0_Track3
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track5
	dw Intro_Subsong0_LinkerBlock1

; Position 3
	dw Intro_Subsong0_Track3
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track5
	dw Intro_Subsong0_LinkerBlock1

; Position 4
	dw Intro_Subsong0_Track6
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track7
	dw Intro_Subsong0_LinkerBlock1

; Position 5
	dw Intro_Subsong0_Track8
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track7
	dw Intro_Subsong0_LinkerBlock1

; Position 6
	dw Intro_Subsong0_Track9
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track7
	dw Intro_Subsong0_LinkerBlock1

; Position 7
	dw Intro_Subsong0_Track10
	dw Intro_Subsong0_Track4
	dw Intro_Subsong0_Track7
	dw Intro_Subsong0_LinkerBlock1

Intro_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Intro_Subsong0_DisarkWordForceReference2
	dw Intro_Subsong0_Linker_Loop

Intro_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Intro_Subsong0_DisarkWordForceReference3
	dw Intro_Subsong0_SpeedTrack0	; SpeedTrack address.
Intro_Subsong0_DisarkWordForceReference4
	dw Intro_Subsong0_EventTrack0	; EventTrack address.
Intro_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Intro_Subsong0_DisarkWordForceReference5
	dw Intro_Subsong0_SpeedTrack1	; SpeedTrack address.
Intro_Subsong0_DisarkWordForceReference6
	dw Intro_Subsong0_EventTrack0	; EventTrack address.

Intro_Subsong0_Track0
	db 242
	db 3	; New Instrument (3).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track1
	db 223
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 30	; Waits for 31 lines.

	db 34
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track2
	db 199
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 7
	db 61, 6	; Waits for 7 lines.

	db 7
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 13
	db 61, 26	; Waits for 27 lines.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track3
	db 178
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track4
	db 159
	db 1	; New Instrument (1).
	db 61, 30	; Waits for 31 lines.

	db 34
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track5
	db 135
	db 2	; New Instrument (2).
	db 61, 14	; Waits for 15 lines.

	db 7
	db 61, 6	; Waits for 7 lines.

	db 7
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 13
	db 61, 26	; Waits for 27 lines.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track6
	db 235
	db 4	; New Instrument (4).
	db 3	; Index to an effect block.
	db 61, 22	; Waits for 23 lines.

	db 45
	db 61, 6	; Waits for 7 lines.

	db 46
	db 61, 22	; Waits for 23 lines.

	db 48
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track7
	db 135
	db 2	; New Instrument (2).
	db 61, 22	; Waits for 23 lines.

	db 7
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 13
	db 61, 26	; Waits for 27 lines.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track8
	db 177
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 55
	db 61, 6	; Waits for 7 lines.

	db 49
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track9
	db 183
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 49
	db 61, 22	; Waits for 23 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Intro_Subsong0_Track10
	db 166
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 33
	db 61, 6	; Waits for 7 lines.

	db 34
	db 61, 14	; Waits for 15 lines.

	db 46
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Intro_Subsong0_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.
Intro_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Intro_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Intro_Subsong0_DisarkByteRegionEnd0
