; Sound Effects for song Untitled, version 2.0, generated by Arkos Tracker 2.

Untitled_SoundEffects

; The sound effects, starting at 1.
	dw Untitled_SoundEffects_Sound1	; Sound effect 1.
	dw Untitled_SoundEffects_Sound2	; Sound effect 2.
	dw Untitled_SoundEffects_Sound3	; Sound effect 3.
	dw Untitled_SoundEffects_Sound4	; Sound effect 4.
	dw Untitled_SoundEffects_Sound5	; Sound effect 5.
	dw Untitled_SoundEffects_Sound6	; Sound effect 6.
	dw Untitled_SoundEffects_Sound7	; Sound effect 7.
	dw Untitled_SoundEffects_Sound8	; Sound effect 8.
	dw Untitled_SoundEffects_Sound9	; Sound effect 9.
	dw Untitled_SoundEffects_Sound10	; Sound effect 10.
	dw Untitled_SoundEffects_Sound11	; Sound effect 11.
	dw Untitled_SoundEffects_Sound12	; Sound effect 12.
	dw Untitled_SoundEffects_Sound13	; Sound effect 13.

; Sound effect 1.
Untitled_SoundEffects_Sound1
	db 0	; Speed

Untitled_SoundEffects_Sound1_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 95	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 102	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
Untitled_SoundEffects_Sound2
	db 0	; Speed

Untitled_SoundEffects_Sound2_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 301	; Software period.

	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 319	; Software period.

	db 185	; Soft only. Volume: 14.
	db 2	; Noise: 2.
	dw 402	; Software period.

	db 181	; Soft only. Volume: 13.
	db 16	; Noise: 16.
	dw 213	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 225	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 239	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 358	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 119	; Software period.

	db 153	; Soft only. Volume: 6.
	db 7	; Noise: 7.
	dw 80	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
Untitled_SoundEffects_Sound3
	db 0	; Speed

Untitled_SoundEffects_Sound3_Loop	db 189	; Soft only. Volume: 15.
	db 5	; Noise: 5.
	dw 30	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 60	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 40	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 60	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
Untitled_SoundEffects_Sound4
	db 0	; Speed

Untitled_SoundEffects_Sound4_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 60	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 95	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 47	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 80	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 40	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
Untitled_SoundEffects_Sound5
	db 0	; Speed

Untitled_SoundEffects_Sound5_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 60	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 119	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 89	; Software period.

	db 157	; Soft only. Volume: 7.
	db 15	; Noise: 15.
	dw 119	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 4	; End of the sound effect.

; Sound effect 6.
Untitled_SoundEffects_Sound6
	db 0	; Speed

Untitled_SoundEffects_Sound6_Loop	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 478	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 851	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 1136	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 1276	; Software period.

	db 4	; End of the sound effect.

; Sound effect 7.
Untitled_SoundEffects_Sound7
	db 0	; Speed

Untitled_SoundEffects_Sound7_Loop	db 189	; Soft only. Volume: 15.
	db 6	; Noise: 6.
	dw 1351	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 478	; Software period.

	db 189	; Soft only. Volume: 15.
	db 2	; Noise: 2.
	dw 478	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 676	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 478	; Software period.

	db 4	; End of the sound effect.

; Sound effect 8.
Untitled_SoundEffects_Sound8
	db 0	; Speed

Untitled_SoundEffects_Sound8_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 56	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 106	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 53	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 100	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 50	; Software period.

	db 4	; End of the sound effect.

; Sound effect 9.
Untitled_SoundEffects_Sound9
	db 0	; Speed

Untitled_SoundEffects_Sound9_Loop	db 0	; No soft, no hard. Volume: 0.

	db 4	; End of the sound effect.

; Sound effect 10.
Untitled_SoundEffects_Sound10
	db 0	; Speed

Untitled_SoundEffects_Sound10_Loop	db 19	; Soft and Hard. Env: 10.
	dw 22	; Hardware period.
	dw 89	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 5	; Hardware period.
	dw 86	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 21	; Hardware period.
	dw 82	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 5	; Hardware period.
	dw 80	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 20	; Hardware period.
	dw 78	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 5	; Hardware period.
	dw 76	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 18	; Hardware period.
	dw 73	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 4	; Hardware period.
	dw 70	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 17	; Hardware period.
	dw 66	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 4	; Hardware period.
	dw 64	; Software period.

	db 4	; End of the sound effect.

; Sound effect 11.
Untitled_SoundEffects_Sound11
	db 0	; Speed

Untitled_SoundEffects_Sound11_Loop	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 27	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 30	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 19	; Hardware period.
	dw 301	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 34	; Hardware period.
	dw 536	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 50	; Hardware period.
	dw 804	; Software period.

	db 4	; End of the sound effect.

; Sound effect 12.
Untitled_SoundEffects_Sound12
	db 0	; Speed

Untitled_SoundEffects_Sound12_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 253	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 266	; Software period.

	db 4	; End of the sound effect.

; Sound effect 13.
Untitled_SoundEffects_Sound13
	db 0	; Speed

Untitled_SoundEffects_Sound13_Loop	db 200	; No soft, no hard. Volume: 9.
	db 27	; Noise: 27.

	db 216	; No soft, no hard. Volume: 11.
	db 5	; Noise: 5.

	db 248	; No soft, no hard. Volume: 15.
	db 8	; Noise: 8.

	db 232	; No soft, no hard. Volume: 13.
	db 16	; Noise: 16.

	db 216	; No soft, no hard. Volume: 11.
	db 5	; Noise: 5.

	db 4	; End of the sound effect.

