; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Newsong_SongStart
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
	dw Newsong_FmInstrumentTable
	dw Newsong_ArpeggioTable
	dw Newsong_PitchTable
; Table of the Subsongs.
	dw Newsong_Subsong0

; The Arpeggio table.
Newsong_ArpeggioTable
	dw 0

; The Pitch table.
Newsong_PitchTable
	dw 0

; The FM Instrument table.
Newsong_FmInstrumentTable
	dw Newsong_FmInstrument0

Newsong_FmInstrument0
	db 255	; Speed.

Newsong_FmInstrument0_Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
	dw Newsong_FmInstrument0_Loop	; Loops.

; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Newsong_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
Newsong_Subsong0_Loop
	db 5	; State byte.
	db 63	; New height.
	dw Newsong_Subsong0_Track0, Newsong_Subsong0_Track0, Newsong_Subsong0_Track0	; The tracks.

	db 0	; End of the subsong.
	dw Newsong_Subsong0_Loop

; The Tracks.
Newsong_Subsong0_Track0
	db 61, 63	; Long wait: 64.


