; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Newsong_SongStart
	db "ATLW"	; Format marker (Lightweight).
	db 1	; Format version.
	dw Newsong_FmInstrumentTable
	dw Newsong_ArpeggioTable
	dw Newsong_PitchTable
; Table of the Subsongs.
	dw Newsong_Subsong0

; The Arpeggio table.
Newsong_ArpeggioTable
	dw 0
	dw Newsong_Arpeggio1
	dw Newsong_Arpeggio2

; The Pitch table.
Newsong_PitchTable
	dw 0
	dw Newsong_Pitch1

; The FM Instrument table.
Newsong_FmInstrumentTable
	dw Newsong_FmInstrument0
	dw Newsong_FmInstrument1
	dw Newsong_FmInstrument2
	dw Newsong_FmInstrument3
	dw Newsong_FmInstrument4

Newsong_Arpeggio1
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db 8	; Value: 4
	db 8	; Value: 4
	db 8	; Value: 4
	db 14	; Value: 7
	db 14	; Value: 7
	db 14	; Value: 7
	db 24	; Value: 12
	db 24	; Value: 12
	db 24	; Value: 12
	db 32	; Value: 16
	db 32	; Value: 16
	db 32	; Value: 16
	db 38	; Value: 19
	db 38	; Value: 19
	db 38	; Value: 19
	db 1	; End, loop to index 0

Newsong_Arpeggio2
	db 0	; Value: 0
	db 6	; Value: 3
	db 14	; Value: 7
	db 18	; Value: 9
	db 1	; End, loop to index 0

Newsong_Pitch1
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db -2	; Value: -1
	db -2	; Value: -1
	db -2	; Value: -1
	db -4	; Value: -2
	db -4	; Value: -2
	db -4	; Value: -2
	db -2	; Value: -1
	db -2	; Value: -1
	db -2	; Value: -1
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db 2	; Value: 1
	db 2	; Value: 1
	db 2	; Value: 1
	db 4	; Value: 2
	db 4	; Value: 2
	db 4	; Value: 2
	db 2	; Value: 1
	db 2	; Value: 1
	db 2	; Value: 1
	db 1	; End, loop to index 0

Newsong_FmInstrument0
	db 255	; Speed.

Newsong_FmInstrument0_Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
	dw Newsong_FmInstrument0_Loop	; Loops.

Newsong_FmInstrument1
	db 1	; Speed.

	db 125	; Volume: 15.
	dw -6	; Pitch: -6.

	db 121	; Volume: 14.
	dw -5	; Pitch: -5.

	db 117	; Volume: 13.
	dw -4	; Pitch: -4.

	db 113	; Volume: 12.
	dw -3	; Pitch: -3.

	db 109	; Volume: 11.
	dw -2	; Pitch: -2.

	db 105	; Volume: 10.
	dw -1	; Pitch: -1.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
	dw Newsong_FmInstrument0_Loop	; Loop to silence.

Newsong_FmInstrument2
	db 2	; Speed.

Newsong_FmInstrument2_Loop	db 61	; Volume: 15.

	db 112	; Volume: 14.

	db 4	; End the instrument.
	dw Newsong_FmInstrument2_Loop	; Loops.

Newsong_FmInstrument3
	db 0	; Speed.

Newsong_FmInstrument3_Loop	db 61	; Volume: 15.

	db 189	; Volume: 15.
	db 6	; Arpeggio: 3.

	db 189	; Volume: 15.
	db 14	; Arpeggio: 7.

	db 4	; End the instrument.
	dw Newsong_FmInstrument3_Loop	; Loops.

Newsong_FmInstrument4
	db 0	; Speed.

Newsong_FmInstrument4_Loop	db 189	; Volume: 15.
	db 24	; Arpeggio: 12.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
	dw Newsong_FmInstrument4_Loop	; Loops.

; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Newsong_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
Newsong_Subsong0_Loop
	db 5	; State byte.
	db 20	; New height.
	dw Newsong_Subsong0_Track0, Newsong_Subsong0_Track1, Newsong_Subsong0_Track1	; The tracks.

; Pattern 1
	db 5	; State byte.
	db 87	; New height.
	dw Newsong_Subsong0_Track2, Newsong_Subsong0_Track1, Newsong_Subsong0_Track1	; The tracks.

; Pattern 2
	db 5	; State byte.
	db 47	; New height.
	dw Newsong_Subsong0_Track3, Newsong_Subsong0_Track1, Newsong_Subsong0_Track1	; The tracks.

	db 0	; End of the subsong.
	dw Newsong_Subsong0_Loop

; The Tracks.
Newsong_Subsong0_Track0
	db 216	; Note: 48.
	db 2	; New instrument: 1.
	db 0	; Reset + inverted volume.
	db 190	; Short wait: 3.

	db 26	; Note: 50.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 154	; Note: 50.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 62	; Short wait: 1.

	db 156	; Note: 52.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 29	; Note: 53.
	db 190	; Short wait: 3.

	db 31	; Note: 55.
	db 61, 71	; Long wait: 72.


Newsong_Subsong0_Track1
	db 61, 87	; Long wait: 88.


Newsong_Subsong0_Track2
	db 211	; Note: 43.
	db 6	; New instrument: 3.
	db 0	; Reset + inverted volume.
	db 61, 14	; Long wait: 15.

	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 26	; Note: 50.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 29	; Note: 53.
	db 62	; Short wait: 1.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 62	; Short wait: 1.

	db 36	; Note: 60.
	db 62	; Short wait: 1.

	db 60	; No note, effects only.
	db 127	; Pitch down: 256.
	dw 256	; Pitch.
	db 61, 6	; Long wait: 7.

	db 60	; No note, effects only.
	db 96	; Pitch down: 0.
	db 190	; Short wait: 3.

	db 88	; Note: 48.
	db 0	; Reset + inverted volume.
	db 62	; Short wait: 1.

	db 60	; No note, effects only.
	db 33	; Arpeggio table: 1.
	db 126	; Short wait: 2.

	db 60	; No note, effects only.
	db 65	; Pitch table: 1.
	db 61, 9	; Long wait: 10.

	db 60	; No note, effects only.
	db 64	; Pitch table: 0.
	db 190	; Short wait: 3.

	db 60	; No note, effects only.
	db 32	; Arpeggio table: 0.
	db 190	; Short wait: 3.

	db 60	; No note, effects only.
	db 65	; Pitch table: 1.
	db 254	; Short wait: 4.

	db 60	; No note, effects only.
	db 0	; Reset + inverted volume.
	db 61, 9	; Long wait: 10.


Newsong_Subsong0_Track3
	db 216	; Note: 48.
	db 8	; New instrument: 4.
	db 160	; Volume + Arpeggio Table.
	db 2	; Arpeggio number.
	db 61, 5	; Long wait: 6.

	db 60	; No note, effects only.
	db 160	; Volume + Arpeggio Table.
	db 0	; Arpeggio number.
	db 61, 6	; Long wait: 7.

	db 60	; No note, effects only.
	db 192	; Reset + inverted volume + Arpeggio Table.
	db 2	; Arpeggio number.
	db 61, 7	; Long wait: 8.

	db 60	; No note, effects only.
	db 192	; Reset + inverted volume + Arpeggio Table.
	db 1	; Arpeggio number.
	db 61, 7	; Long wait: 8.

	db 60	; No note, effects only.
	db 192	; Reset + inverted volume + Arpeggio Table.
	db 0	; Arpeggio number.
	db 61, 4	; Long wait: 5.

	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 61, 47	; Long wait: 48.


